name: 'Test'
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  buildTest:
    runs-on: ubuntu-latest

    strategy:
        node-version: '14'

    steps:
    - uses: actions/checkout@v2
    - name: Use node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: yarn
    - run: yarn test:unit